    language: python
    python: 
      - "3.6"
    services: 
      - mysql
    env: 
      -DJANGO=2.0 DB=mysql
    before_script: 
      - mysql -e 'create database test;' -u root
    script: 
      - python manage.py test
